server:
  port: 8123
  servlet:
    context-path: /api
    #cookie
    session:
      cookie:
        #30天过期
        max-age: 2592000
spring:
  #  日志输出颜色
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: cbj-picture-backend
  #    数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yu_picture
    username: root
    password: root
  # Redis配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000 #5s没连上redis会报错
  #session
  session:
    store-type: redis
    #30天后过期
    timeout: 2592000
  #  开放更大的文件上传
  servlet:
    multipart:
      max-file-size: 10MB
  # 空间图片分表
  shardingsphere:
    datasource:
      names: yu_picture
      yu_picture:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/yu_picture
        username: root
        password: root
    rules:
      sharding:
        tables:
          picture:
            actual-data-nodes: yu_picture.picture  # 动态分表
            table-strategy:
              standard:
                sharding-column: spaceId
                sharding-algorithm-name: picture_sharding_algorithm  # 使用自定义分片算法
        sharding-algorithms:
          picture_sharding_algorithm:
            type: CLASS_BASED
            props:
              strategy: standard
              algorithmClassName: com.yupi.cbjpicturebackend.manager.sharding.PictureShardingAlgorithm
    props:
      sql-show: true



  #使用本地local-yaml文件
  profiles:
    active: local
mybatis-plus:
  configuration:
    # 不会自动把数据库的下划线列名映射到驼峰字段。
    map-underscore-to-camel-case: false
    #    仅在开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    enable-sql-runner: true
    db-config:
      #      逻辑删除(软删除)
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 #逻辑已删除（1）
      logic-not-delete-value: 0 #逻辑未删除（0）
#接口文档
knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.yupi.cbjpicturebackend.controller
